// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vdj.h for the primary calling header

#ifndef VERILATED_VDJ___024ROOT_H_
#define VERILATED_VDJ___024ROOT_H_  // guard

#include "verilated.h"


class Vdj__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vdj___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk_clk,0,0);
        CData/*0:0*/ dj__DOT__rst_controller__DOT__merged_reset;
        CData/*0:0*/ dj__DOT__rst_controller__DOT__genblk1__DOT__alt_rst_sync_uq1__DOT__altera_reset_synchronizer_int_chain_out;
        VL_IN8(dj_0_avalon_slave_0_write,0,0);
        VL_IN8(dj_0_avalon_slave_0_read,0,0);
        VL_IN8(dj_0_avalon_slave_0_address,0,0);
        VL_OUT8(dj_0_left_stream_interrupt_irq,0,0);
        VL_OUT8(dj_0_right_stream_interrupt_irq,0,0);
        VL_IN8(reset_reset_n,0,0);
        CData/*0:0*/ dj__DOT__dj_0_codec_left_fifo_sink_valid;
        CData/*0:0*/ dj__DOT__dj_0_codec_right_fifo_sink_valid;
        CData/*0:0*/ dj__DOT__dj_0_left_fifo_sink_valid;
        CData/*0:0*/ dj__DOT__codec_left_fifo_out_valid;
        CData/*0:0*/ dj__DOT__codec_right_fifo_out_valid;
        CData/*0:0*/ dj__DOT__left_sc_fifo_out_valid;
        CData/*0:0*/ dj__DOT__right_sc_fifo_out_valid;
        CData/*0:0*/ dj__DOT__dj_0_right_fifo_sink_valid;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft_o_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft_i_reset;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft_o_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_lpf_o_ce;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_lpf_o_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__right_fft_o_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__right_ifft_i_ce;
        CData/*0:0*/ dj__DOT__dj_0__DOT__right_ifft_i_reset;
        CData/*0:0*/ dj__DOT__dj_0__DOT__right_ifft_o_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__right_lpf_o_ce;
        CData/*0:0*/ dj__DOT__dj_0__DOT__right_lpf_o_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_r_syncd;
        CData/*0:0*/ dj__DOT__dj_0__DOT__right_r_syncd;
        CData/*2:0*/ dj__DOT__dj_0__DOT__ctr;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__br_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__w_s512;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__w_s256;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__w_s128;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__w_s64;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__w_s32;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__w_s16;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__w_s8;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__w_s4;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__w_s2;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__r_br_started;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT____Vcellinp__revstage__i_ce;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__wait_for_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__ib_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__b_started;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__ob_sync;
        CData/*7:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__nxt_oaddr;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__wait_for_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__ib_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__b_started;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__ob_sync;
        CData/*7:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__iaddr;
        CData/*7:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__oaddr;
        CData/*6:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__nxt_oaddr;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__wait_for_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__ib_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__b_started;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__ob_sync;
        CData/*6:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__iaddr;
    };
    struct {
        CData/*6:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__oaddr;
        CData/*5:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__nxt_oaddr;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__wait_for_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__ib_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__b_started;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__ob_sync;
        CData/*5:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__iaddr;
        CData/*5:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__oaddr;
        CData/*4:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__nxt_oaddr;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__wait_for_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__ib_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__b_started;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__ob_sync;
        CData/*4:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__iaddr;
        CData/*4:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__oaddr;
        CData/*3:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__nxt_oaddr;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__wait_for_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__ib_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__b_started;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__ob_sync;
        CData/*3:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__iaddr;
        CData/*3:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__oaddr;
        CData/*2:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__nxt_oaddr;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__wait_for_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__ib_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__b_started;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__ob_sync;
        CData/*2:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__iaddr;
        CData/*2:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__oaddr;
        CData/*1:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__nxt_oaddr;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_4__DOT__wait_for_sync;
        CData/*2:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_4__DOT__pipeline;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_2__DOT__wait_for_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_2__DOT__stage;
        CData/*1:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_2__DOT__sync_pipe;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__revstage__DOT__in_reset;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__br_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__w_s512;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__w_s256;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__w_s128;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__w_s64;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__w_s32;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__w_s16;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__w_s8;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__w_s4;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__w_s2;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__r_br_started;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT____Vcellinp__revstage__i_ce;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__wait_for_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__ib_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__b_started;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__ob_sync;
        CData/*7:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__nxt_oaddr;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
    };
    struct {
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__wait_for_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__ib_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__b_started;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__ob_sync;
        CData/*7:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__iaddr;
        CData/*7:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__oaddr;
        CData/*6:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__nxt_oaddr;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__wait_for_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__ib_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__b_started;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__ob_sync;
        CData/*6:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__iaddr;
        CData/*6:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__oaddr;
        CData/*5:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__nxt_oaddr;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__wait_for_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__ib_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__b_started;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__ob_sync;
        CData/*5:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__iaddr;
        CData/*5:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__oaddr;
        CData/*4:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__nxt_oaddr;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__wait_for_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__ib_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__b_started;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__ob_sync;
        CData/*4:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__iaddr;
        CData/*4:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__oaddr;
        CData/*3:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__nxt_oaddr;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__wait_for_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__ib_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__b_started;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__ob_sync;
        CData/*3:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__iaddr;
        CData/*3:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__oaddr;
        CData/*2:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__nxt_oaddr;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__wait_for_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__ib_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__b_started;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__ob_sync;
        CData/*2:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__iaddr;
        CData/*2:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__oaddr;
        CData/*1:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__nxt_oaddr;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_4__DOT__wait_for_sync;
        CData/*2:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_4__DOT__pipeline;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_2__DOT__wait_for_sync;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_2__DOT__stage;
        CData/*1:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_2__DOT__sync_pipe;
        CData/*0:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__revstage__DOT__in_reset;
        CData/*1:0*/ dj__DOT__codec_left_fifo__DOT__csr_address;
        CData/*0:0*/ dj__DOT__codec_left_fifo__DOT__csr_write;
        CData/*0:0*/ dj__DOT__codec_left_fifo__DOT__csr_read;
    };
    struct {
        CData/*0:0*/ dj__DOT__codec_left_fifo__DOT__read;
        CData/*0:0*/ dj__DOT__codec_left_fifo__DOT__write;
        CData/*0:0*/ dj__DOT__codec_left_fifo__DOT__empty;
        CData/*0:0*/ dj__DOT__codec_left_fifo__DOT__next_empty;
        CData/*0:0*/ dj__DOT__codec_left_fifo__DOT__full;
        CData/*0:0*/ dj__DOT__codec_left_fifo__DOT__next_full;
        CData/*0:0*/ dj__DOT__codec_left_fifo__DOT__internal_out_valid;
        CData/*0:0*/ dj__DOT__codec_left_fifo__DOT__internal_out_ready;
        CData/*0:0*/ dj__DOT__codec_left_fifo__DOT__drop_on_error_en;
        CData/*0:0*/ dj__DOT__codec_left_fifo__DOT__error_in_pkt;
        CData/*0:0*/ dj__DOT__codec_left_fifo__DOT__pkt_has_started;
        CData/*0:0*/ dj__DOT__codec_left_fifo__DOT__sop_has_left_fifo;
        CData/*0:0*/ dj__DOT__codec_left_fifo__DOT__fifo_too_small_r;
        CData/*0:0*/ dj__DOT__codec_left_fifo__DOT__pkt_cnt_eq_zero;
        CData/*0:0*/ dj__DOT__codec_left_fifo__DOT__pkt_cnt_eq_one;
        CData/*0:0*/ dj__DOT__codec_left_fifo__DOT__wait_for_threshold;
        CData/*0:0*/ dj__DOT__codec_left_fifo__DOT__pkt_mode;
        CData/*0:0*/ dj__DOT__codec_left_fifo__DOT__wait_for_pkt;
        CData/*0:0*/ dj__DOT__codec_left_fifo__DOT__in_pkt_eop_arrive;
        CData/*0:0*/ dj__DOT__codec_left_fifo__DOT__out_pkt_leave;
        CData/*0:0*/ dj__DOT__codec_left_fifo__DOT__in_pkt_start;
        CData/*0:0*/ dj__DOT__codec_left_fifo__DOT__in_pkt_error;
        CData/*0:0*/ dj__DOT__codec_left_fifo__DOT__fifo_too_small;
        CData/*0:0*/ dj__DOT__codec_left_fifo__DOT__out_pkt_sop_leave;
        CData/*0:0*/ dj__DOT__codec_left_fifo__DOT__fifo_fill_level_lt_cut_through_threshold;
        CData/*1:0*/ dj__DOT__codec_right_fifo__DOT__csr_address;
        CData/*0:0*/ dj__DOT__codec_right_fifo__DOT__csr_write;
        CData/*0:0*/ dj__DOT__codec_right_fifo__DOT__csr_read;
        CData/*0:0*/ dj__DOT__codec_right_fifo__DOT__read;
        CData/*0:0*/ dj__DOT__codec_right_fifo__DOT__write;
        CData/*0:0*/ dj__DOT__codec_right_fifo__DOT__empty;
        CData/*0:0*/ dj__DOT__codec_right_fifo__DOT__next_empty;
        CData/*0:0*/ dj__DOT__codec_right_fifo__DOT__full;
        CData/*0:0*/ dj__DOT__codec_right_fifo__DOT__next_full;
        CData/*0:0*/ dj__DOT__codec_right_fifo__DOT__internal_out_valid;
        CData/*0:0*/ dj__DOT__codec_right_fifo__DOT__internal_out_ready;
        CData/*0:0*/ dj__DOT__codec_right_fifo__DOT__drop_on_error_en;
        CData/*0:0*/ dj__DOT__codec_right_fifo__DOT__error_in_pkt;
        CData/*0:0*/ dj__DOT__codec_right_fifo__DOT__pkt_has_started;
        CData/*0:0*/ dj__DOT__codec_right_fifo__DOT__sop_has_left_fifo;
        CData/*0:0*/ dj__DOT__codec_right_fifo__DOT__fifo_too_small_r;
        CData/*0:0*/ dj__DOT__codec_right_fifo__DOT__pkt_cnt_eq_zero;
        CData/*0:0*/ dj__DOT__codec_right_fifo__DOT__pkt_cnt_eq_one;
        CData/*0:0*/ dj__DOT__codec_right_fifo__DOT__wait_for_threshold;
        CData/*0:0*/ dj__DOT__codec_right_fifo__DOT__pkt_mode;
        CData/*0:0*/ dj__DOT__codec_right_fifo__DOT__wait_for_pkt;
        CData/*0:0*/ dj__DOT__codec_right_fifo__DOT__in_pkt_eop_arrive;
        CData/*0:0*/ dj__DOT__codec_right_fifo__DOT__out_pkt_leave;
        CData/*0:0*/ dj__DOT__codec_right_fifo__DOT__in_pkt_start;
        CData/*0:0*/ dj__DOT__codec_right_fifo__DOT__in_pkt_error;
        CData/*0:0*/ dj__DOT__codec_right_fifo__DOT__fifo_too_small;
        CData/*0:0*/ dj__DOT__codec_right_fifo__DOT__out_pkt_sop_leave;
        CData/*0:0*/ dj__DOT__codec_right_fifo__DOT__fifo_fill_level_lt_cut_through_threshold;
        CData/*1:0*/ dj__DOT__left_sc_fifo__DOT__csr_address;
        CData/*0:0*/ dj__DOT__left_sc_fifo__DOT__csr_write;
        CData/*0:0*/ dj__DOT__left_sc_fifo__DOT__csr_read;
        CData/*0:0*/ dj__DOT__left_sc_fifo__DOT__read;
        CData/*0:0*/ dj__DOT__left_sc_fifo__DOT__write;
        CData/*0:0*/ dj__DOT__left_sc_fifo__DOT__empty;
        CData/*0:0*/ dj__DOT__left_sc_fifo__DOT__next_empty;
        CData/*0:0*/ dj__DOT__left_sc_fifo__DOT__full;
        CData/*0:0*/ dj__DOT__left_sc_fifo__DOT__next_full;
        CData/*0:0*/ dj__DOT__left_sc_fifo__DOT__internal_out_valid;
        CData/*0:0*/ dj__DOT__left_sc_fifo__DOT__internal_out_ready;
    };
    struct {
        CData/*0:0*/ dj__DOT__left_sc_fifo__DOT__drop_on_error_en;
        CData/*0:0*/ dj__DOT__left_sc_fifo__DOT__error_in_pkt;
        CData/*0:0*/ dj__DOT__left_sc_fifo__DOT__pkt_has_started;
        CData/*0:0*/ dj__DOT__left_sc_fifo__DOT__sop_has_left_fifo;
        CData/*0:0*/ dj__DOT__left_sc_fifo__DOT__fifo_too_small_r;
        CData/*0:0*/ dj__DOT__left_sc_fifo__DOT__pkt_cnt_eq_zero;
        CData/*0:0*/ dj__DOT__left_sc_fifo__DOT__pkt_cnt_eq_one;
        CData/*0:0*/ dj__DOT__left_sc_fifo__DOT__wait_for_threshold;
        CData/*0:0*/ dj__DOT__left_sc_fifo__DOT__pkt_mode;
        CData/*0:0*/ dj__DOT__left_sc_fifo__DOT__wait_for_pkt;
        CData/*0:0*/ dj__DOT__left_sc_fifo__DOT__in_pkt_eop_arrive;
        CData/*0:0*/ dj__DOT__left_sc_fifo__DOT__out_pkt_leave;
        CData/*0:0*/ dj__DOT__left_sc_fifo__DOT__in_pkt_start;
        CData/*0:0*/ dj__DOT__left_sc_fifo__DOT__in_pkt_error;
        CData/*0:0*/ dj__DOT__left_sc_fifo__DOT__fifo_too_small;
        CData/*0:0*/ dj__DOT__left_sc_fifo__DOT__out_pkt_sop_leave;
        CData/*0:0*/ dj__DOT__left_sc_fifo__DOT__fifo_fill_level_lt_cut_through_threshold;
        CData/*1:0*/ dj__DOT__right_sc_fifo__DOT__csr_address;
        CData/*0:0*/ dj__DOT__right_sc_fifo__DOT__csr_write;
        CData/*0:0*/ dj__DOT__right_sc_fifo__DOT__csr_read;
        CData/*0:0*/ dj__DOT__right_sc_fifo__DOT__read;
        CData/*0:0*/ dj__DOT__right_sc_fifo__DOT__write;
        CData/*0:0*/ dj__DOT__right_sc_fifo__DOT__empty;
        CData/*0:0*/ dj__DOT__right_sc_fifo__DOT__next_empty;
        CData/*0:0*/ dj__DOT__right_sc_fifo__DOT__full;
        CData/*0:0*/ dj__DOT__right_sc_fifo__DOT__next_full;
        CData/*0:0*/ dj__DOT__right_sc_fifo__DOT__internal_out_valid;
        CData/*0:0*/ dj__DOT__right_sc_fifo__DOT__internal_out_ready;
        CData/*0:0*/ dj__DOT__right_sc_fifo__DOT__drop_on_error_en;
        CData/*0:0*/ dj__DOT__right_sc_fifo__DOT__error_in_pkt;
        CData/*0:0*/ dj__DOT__right_sc_fifo__DOT__pkt_has_started;
        CData/*0:0*/ dj__DOT__right_sc_fifo__DOT__sop_has_left_fifo;
        CData/*0:0*/ dj__DOT__right_sc_fifo__DOT__fifo_too_small_r;
        CData/*0:0*/ dj__DOT__right_sc_fifo__DOT__pkt_cnt_eq_zero;
        CData/*0:0*/ dj__DOT__right_sc_fifo__DOT__pkt_cnt_eq_one;
        CData/*0:0*/ dj__DOT__right_sc_fifo__DOT__wait_for_threshold;
        CData/*0:0*/ dj__DOT__right_sc_fifo__DOT__pkt_mode;
        CData/*0:0*/ dj__DOT__right_sc_fifo__DOT__wait_for_pkt;
        CData/*0:0*/ dj__DOT__right_sc_fifo__DOT__in_pkt_eop_arrive;
        CData/*0:0*/ dj__DOT__right_sc_fifo__DOT__out_pkt_leave;
        CData/*0:0*/ dj__DOT__right_sc_fifo__DOT__in_pkt_start;
        CData/*0:0*/ dj__DOT__right_sc_fifo__DOT__in_pkt_error;
        CData/*0:0*/ dj__DOT__right_sc_fifo__DOT__fifo_too_small;
        CData/*0:0*/ dj__DOT__right_sc_fifo__DOT__out_pkt_sop_leave;
        CData/*0:0*/ dj__DOT__right_sc_fifo__DOT__fifo_fill_level_lt_cut_through_threshold;
        CData/*4:0*/ dj__DOT__rst_controller__DOT__altera_reset_synchronizer_int_chain;
        CData/*3:0*/ dj__DOT__rst_controller__DOT__r_sync_rst_chain;
        CData/*0:0*/ dj__DOT__rst_controller__DOT__r_sync_rst;
        CData/*0:0*/ dj__DOT__rst_controller__DOT__r_early_rst;
        CData/*1:0*/ dj__DOT__rst_controller__DOT__genblk1__DOT__alt_rst_sync_uq1__DOT__altera_reset_synchronizer_int_chain;
        CData/*1:0*/ dj__DOT__rst_controller__DOT__genblk1__DOT__alt_rst_req_sync_uq1__DOT__altera_reset_synchronizer_int_chain;
        CData/*0:0*/ dj__DOT__rst_controller__DOT__genblk1__DOT__alt_rst_req_sync_uq1__DOT__altera_reset_synchronizer_int_chain_out;
        CData/*0:0*/ __Vdlyvset__dj__DOT__codec_left_fifo__DOT__mem__v0;
        CData/*0:0*/ __Vdlyvset__dj__DOT__codec_right_fifo__DOT__mem__v0;
        CData/*0:0*/ __Vdlyvset__dj__DOT__left_sc_fifo__DOT__mem__v0;
        CData/*0:0*/ __Vdlyvset__dj__DOT__right_sc_fifo__DOT__mem__v0;
        CData/*1:0*/ __Vdly__dj__DOT__rst_controller__DOT__genblk1__DOT__alt_rst_sync_uq1__DOT__altera_reset_synchronizer_int_chain;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__dj__DOT__rst_controller__DOT__genblk1__DOT__alt_rst_sync_uq1__DOT__altera_reset_synchronizer_int_chain_out__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__dj__DOT__rst_controller__DOT__merged_reset__0;
        CData/*0:0*/ __VactContinue;
        VL_IN16(dj_0_avalon_slave_0_writedata,15,0);
    };
    struct {
        VL_OUT16(dj_0_avalon_slave_0_readdata,15,0);
        SData/*9:0*/ dj__DOT__dj_0__DOT__right_lpf_cutoff;
        SData/*8:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__iaddr;
        SData/*8:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__oaddr;
        SData/*8:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_4__DOT__iaddr;
        SData/*9:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__revstage__DOT__wraddr;
        SData/*9:0*/ dj__DOT__dj_0__DOT__left_lpf__DOT__bin_idx;
        SData/*8:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__iaddr;
        SData/*8:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__oaddr;
        SData/*8:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_4__DOT__iaddr;
        SData/*9:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__revstage__DOT__wraddr;
        SData/*9:0*/ dj__DOT__codec_left_fifo__DOT__wr_ptr;
        SData/*9:0*/ dj__DOT__codec_left_fifo__DOT__rd_ptr;
        SData/*9:0*/ dj__DOT__codec_left_fifo__DOT__next_wr_ptr;
        SData/*9:0*/ dj__DOT__codec_left_fifo__DOT__next_rd_ptr;
        SData/*15:0*/ dj__DOT__codec_left_fifo__DOT__internal_out_payload;
        SData/*15:0*/ dj__DOT__codec_left_fifo__DOT__out_payload;
        SData/*10:0*/ dj__DOT__codec_left_fifo__DOT__fifo_fill_level;
        SData/*10:0*/ dj__DOT__codec_left_fifo__DOT__fill_level;
        SData/*15:0*/ dj__DOT__codec_left_fifo__DOT__pkt_cnt;
        SData/*9:0*/ dj__DOT__codec_right_fifo__DOT__wr_ptr;
        SData/*9:0*/ dj__DOT__codec_right_fifo__DOT__rd_ptr;
        SData/*9:0*/ dj__DOT__codec_right_fifo__DOT__next_wr_ptr;
        SData/*9:0*/ dj__DOT__codec_right_fifo__DOT__next_rd_ptr;
        SData/*15:0*/ dj__DOT__codec_right_fifo__DOT__internal_out_payload;
        SData/*15:0*/ dj__DOT__codec_right_fifo__DOT__out_payload;
        SData/*10:0*/ dj__DOT__codec_right_fifo__DOT__fifo_fill_level;
        SData/*10:0*/ dj__DOT__codec_right_fifo__DOT__fill_level;
        SData/*15:0*/ dj__DOT__codec_right_fifo__DOT__pkt_cnt;
        SData/*9:0*/ dj__DOT__left_sc_fifo__DOT__wr_ptr;
        SData/*9:0*/ dj__DOT__left_sc_fifo__DOT__rd_ptr;
        SData/*9:0*/ dj__DOT__left_sc_fifo__DOT__next_wr_ptr;
        SData/*9:0*/ dj__DOT__left_sc_fifo__DOT__next_rd_ptr;
        SData/*15:0*/ dj__DOT__left_sc_fifo__DOT__internal_out_payload;
        SData/*15:0*/ dj__DOT__left_sc_fifo__DOT__out_payload;
        SData/*10:0*/ dj__DOT__left_sc_fifo__DOT__fifo_fill_level;
        SData/*10:0*/ dj__DOT__left_sc_fifo__DOT__fill_level;
        SData/*15:0*/ dj__DOT__left_sc_fifo__DOT__pkt_cnt;
        SData/*9:0*/ dj__DOT__right_sc_fifo__DOT__wr_ptr;
        SData/*9:0*/ dj__DOT__right_sc_fifo__DOT__rd_ptr;
        SData/*9:0*/ dj__DOT__right_sc_fifo__DOT__next_wr_ptr;
        SData/*9:0*/ dj__DOT__right_sc_fifo__DOT__next_rd_ptr;
        SData/*15:0*/ dj__DOT__right_sc_fifo__DOT__internal_out_payload;
        SData/*15:0*/ dj__DOT__right_sc_fifo__DOT__out_payload;
        SData/*10:0*/ dj__DOT__right_sc_fifo__DOT__fifo_fill_level;
        SData/*10:0*/ dj__DOT__right_sc_fifo__DOT__fill_level;
        SData/*15:0*/ dj__DOT__right_sc_fifo__DOT__pkt_cnt;
        SData/*9:0*/ __Vdlyvdim0__dj__DOT__codec_left_fifo__DOT__mem__v0;
        SData/*15:0*/ __Vdlyvval__dj__DOT__codec_left_fifo__DOT__mem__v0;
        SData/*9:0*/ __Vdlyvdim0__dj__DOT__codec_right_fifo__DOT__mem__v0;
        SData/*15:0*/ __Vdlyvval__dj__DOT__codec_right_fifo__DOT__mem__v0;
        SData/*9:0*/ __Vdlyvdim0__dj__DOT__left_sc_fifo__DOT__mem__v0;
        SData/*15:0*/ __Vdlyvval__dj__DOT__left_sc_fifo__DOT__mem__v0;
        SData/*9:0*/ __Vdlyvdim0__dj__DOT__right_sc_fifo__DOT__mem__v0;
        SData/*15:0*/ __Vdlyvval__dj__DOT__right_sc_fifo__DOT__mem__v0;
        IData/*31:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__ib_a;
        IData/*31:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__ib_b;
        IData/*31:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        IData/*31:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        IData/*19:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*19:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*16:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*16:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*16:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
    };
    struct {
        IData/*16:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*16:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*16:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*16:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*16:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*19:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*19:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*16:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*16:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*20:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*17:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*20:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*20:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*17:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*17:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*17:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*17:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*17:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*17:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*17:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*17:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*20:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*20:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*17:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*17:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*21:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*18:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*21:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*21:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*18:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*18:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*18:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*18:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*17:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*17:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*17:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*17:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*21:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*21:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*18:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*18:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*22:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*19:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*21:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*21:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*18:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*18:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*18:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*18:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*18:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*18:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*18:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*18:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*21:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*21:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*18:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*18:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*22:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*19:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*22:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*22:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*19:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*19:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*19:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
    };
    struct {
        IData/*19:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*18:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*18:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*18:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*18:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*22:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*22:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*19:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*19:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*23:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*20:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*22:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*22:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*19:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*19:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*19:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*19:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*19:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*19:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*19:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*19:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*22:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*22:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*19:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*19:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*23:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*20:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*23:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*23:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*20:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*20:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*20:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*20:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*19:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*19:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*19:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*19:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*23:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*23:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*20:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*20:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*24:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*21:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*20:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_4__DOT__sum_r;
        IData/*20:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_4__DOT__sum_i;
        IData/*20:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_4__DOT__diff_r;
        IData/*20:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_4__DOT__diff_i;
        IData/*20:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_4__DOT__ob_b_r;
        IData/*20:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_4__DOT__ob_b_i;
        IData/*20:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_4__DOT__rnd_sum_r;
        IData/*20:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_4__DOT__rnd_sum_i;
        IData/*20:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_4__DOT__rnd_diff_r;
        IData/*20:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_4__DOT__rnd_diff_i;
        IData/*20:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_2__DOT__m_r;
        IData/*20:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_2__DOT__m_i;
        IData/*21:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_2__DOT__rnd_r;
        IData/*21:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_2__DOT__rnd_i;
        IData/*21:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_2__DOT__sto_r;
        IData/*21:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_2__DOT__sto_i;
        IData/*20:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_2__DOT__o_r;
        IData/*20:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_2__DOT__o_i;
        IData/*24:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*24:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*21:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
    };
    struct {
        IData/*21:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*21:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*21:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*21:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*21:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*21:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*21:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*24:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*24:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*21:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*21:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*25:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*22:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*25:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*25:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*22:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*22:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*22:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*22:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*22:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*22:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*22:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*22:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*25:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*25:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*22:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*22:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*26:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*23:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*26:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*26:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*23:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*23:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*23:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*23:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*22:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*22:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*22:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*22:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*26:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*26:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*23:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*23:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*27:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*24:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*26:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*26:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*23:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*23:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*23:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*23:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*23:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*23:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*23:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*23:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*26:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*26:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*23:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*23:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*27:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*24:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*27:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*27:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*24:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
    };
    struct {
        IData/*24:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*24:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*24:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*23:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*23:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*23:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*23:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*27:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*27:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*24:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*24:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*28:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*25:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*27:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*27:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*24:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*24:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*24:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*24:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*24:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*24:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*24:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*24:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*27:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*27:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*24:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*24:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*28:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*25:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*28:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*28:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*25:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*25:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*25:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*25:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*24:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*24:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*24:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*24:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*28:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*28:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*25:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*25:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*29:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*26:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*25:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_4__DOT__sum_r;
        IData/*25:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_4__DOT__sum_i;
        IData/*25:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_4__DOT__diff_r;
        IData/*25:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_4__DOT__diff_i;
        IData/*25:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_4__DOT__ob_b_r;
        IData/*25:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_4__DOT__ob_b_i;
        IData/*25:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_4__DOT__rnd_sum_r;
        IData/*25:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_4__DOT__rnd_sum_i;
        IData/*25:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_4__DOT__rnd_diff_r;
        IData/*25:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_4__DOT__rnd_diff_i;
        IData/*25:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_2__DOT__m_r;
        IData/*25:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_2__DOT__m_i;
        IData/*26:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_2__DOT__rnd_r;
        IData/*26:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_2__DOT__rnd_i;
        IData/*26:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_2__DOT__sto_r;
        IData/*26:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_2__DOT__sto_i;
        IData/*25:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_2__DOT__o_r;
        IData/*25:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_2__DOT__o_i;
        IData/*31:0*/ dj__DOT__codec_left_fifo__DOT__csr_writedata;
    };
    struct {
        IData/*31:0*/ dj__DOT__codec_left_fifo__DOT__csr_readdata;
        VlWide<32>/*1023:0*/ dj__DOT__codec_left_fifo__DOT__mem_used;
        IData/*23:0*/ dj__DOT__codec_left_fifo__DOT__almost_full_threshold;
        IData/*23:0*/ dj__DOT__codec_left_fifo__DOT__almost_empty_threshold;
        IData/*23:0*/ dj__DOT__codec_left_fifo__DOT__cut_through_threshold;
        IData/*31:0*/ dj__DOT__codec_left_fifo__DOT__log2ceil__Vstatic__i;
        IData/*31:0*/ dj__DOT__codec_right_fifo__DOT__csr_writedata;
        IData/*31:0*/ dj__DOT__codec_right_fifo__DOT__csr_readdata;
        VlWide<32>/*1023:0*/ dj__DOT__codec_right_fifo__DOT__mem_used;
        IData/*23:0*/ dj__DOT__codec_right_fifo__DOT__almost_full_threshold;
        IData/*23:0*/ dj__DOT__codec_right_fifo__DOT__almost_empty_threshold;
        IData/*23:0*/ dj__DOT__codec_right_fifo__DOT__cut_through_threshold;
        IData/*31:0*/ dj__DOT__codec_right_fifo__DOT__log2ceil__Vstatic__i;
        IData/*31:0*/ dj__DOT__left_sc_fifo__DOT__csr_writedata;
        IData/*31:0*/ dj__DOT__left_sc_fifo__DOT__csr_readdata;
        VlWide<32>/*1023:0*/ dj__DOT__left_sc_fifo__DOT__mem_used;
        IData/*23:0*/ dj__DOT__left_sc_fifo__DOT__almost_full_threshold;
        IData/*23:0*/ dj__DOT__left_sc_fifo__DOT__almost_empty_threshold;
        IData/*23:0*/ dj__DOT__left_sc_fifo__DOT__cut_through_threshold;
        IData/*31:0*/ dj__DOT__left_sc_fifo__DOT__log2ceil__Vstatic__i;
        IData/*31:0*/ dj__DOT__right_sc_fifo__DOT__csr_writedata;
        IData/*31:0*/ dj__DOT__right_sc_fifo__DOT__csr_readdata;
        VlWide<32>/*1023:0*/ dj__DOT__right_sc_fifo__DOT__mem_used;
        IData/*23:0*/ dj__DOT__right_sc_fifo__DOT__almost_full_threshold;
        IData/*23:0*/ dj__DOT__right_sc_fifo__DOT__almost_empty_threshold;
        IData/*23:0*/ dj__DOT__right_sc_fifo__DOT__cut_through_threshold;
        IData/*31:0*/ dj__DOT__right_sc_fifo__DOT__log2ceil__Vstatic__i;
        IData/*31:0*/ __VactIterCount;
        QData/*41:0*/ dj__DOT__dj_0__DOT__left_fft_o_result;
        QData/*51:0*/ dj__DOT__dj_0__DOT__left_ifft_o_result;
        QData/*41:0*/ dj__DOT__dj_0__DOT__left_lpf_o_sample;
        QData/*41:0*/ dj__DOT__dj_0__DOT__right_fft_o_result;
        QData/*41:0*/ dj__DOT__dj_0__DOT__right_ifft_i_sample;
        QData/*51:0*/ dj__DOT__dj_0__DOT__right_ifft_o_result;
        QData/*41:0*/ dj__DOT__dj_0__DOT__right_lpf_o_sample;
        QData/*41:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__br_result;
        QData/*33:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__w_d512;
        QData/*35:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__w_d256;
        QData/*35:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__w_d128;
        QData/*37:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__w_d64;
        QData/*37:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__w_d32;
        QData/*39:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__w_d16;
        QData/*39:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__w_d8;
        QData/*41:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__w_d4;
        QData/*39:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__ib_c;
        QData/*33:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__pre_ovalue;
        QData/*39:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*34:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*34:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*38:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*38:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*34:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*38:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*38:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*36:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*36:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*38:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*33:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__ib_a;
        QData/*33:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__ib_b;
        QData/*41:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__ib_c;
        QData/*35:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__pre_ovalue;
        QData/*33:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*33:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        QData/*41:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
    };
    struct {
        QData/*36:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*36:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*40:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*40:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*36:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*40:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*40:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*38:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*38:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*40:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*35:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__ib_a;
        QData/*35:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__ib_b;
        QData/*43:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__ib_c;
        QData/*35:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__pre_ovalue;
        QData/*35:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*35:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        QData/*43:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*38:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*38:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*42:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*42:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*38:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*42:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*42:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*40:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*40:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*42:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*35:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__ib_a;
        QData/*35:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__ib_b;
        QData/*43:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__ib_c;
        QData/*37:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__pre_ovalue;
        QData/*35:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*35:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        QData/*43:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*38:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*38:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*42:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*42:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*38:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*42:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*42:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*40:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*40:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*42:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*37:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__ib_a;
        QData/*37:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__ib_b;
        QData/*45:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__ib_c;
        QData/*37:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__pre_ovalue;
        QData/*37:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*37:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        QData/*45:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*40:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*40:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*44:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*44:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*40:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*44:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*44:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*42:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*42:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*44:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*37:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__ib_a;
        QData/*37:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__ib_b;
        QData/*45:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__ib_c;
    };
    struct {
        QData/*39:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__pre_ovalue;
        QData/*37:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*37:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        QData/*45:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*40:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*40:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*44:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*44:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*40:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*44:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*44:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*42:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*42:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*44:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*39:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__ib_a;
        QData/*39:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__ib_b;
        QData/*47:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__ib_c;
        QData/*39:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__pre_ovalue;
        QData/*39:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*39:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        QData/*47:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*42:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*42:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*46:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*46:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*42:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*46:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*46:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*44:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*44:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*46:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*41:0*/ dj__DOT__dj_0__DOT__left_fft__DOT__stage_4__DOT__ob_a;
        QData/*51:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__br_result;
        QData/*43:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__w_d512;
        QData/*45:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__w_d256;
        QData/*45:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__w_d128;
        QData/*47:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__w_d64;
        QData/*47:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__w_d32;
        QData/*49:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__w_d16;
        QData/*49:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__w_d8;
        QData/*51:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__w_d4;
        QData/*41:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__ib_a;
        QData/*41:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__ib_b;
        QData/*49:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__ib_c;
        QData/*43:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__pre_ovalue;
        QData/*41:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*41:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        QData/*49:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*44:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*44:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*48:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*48:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*44:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*48:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*48:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*46:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*46:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*48:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*43:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__ib_a;
        QData/*43:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__ib_b;
        QData/*51:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__ib_c;
        QData/*45:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__pre_ovalue;
        QData/*43:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*43:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_right;
    };
    struct {
        QData/*51:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*46:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*46:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*50:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*50:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*46:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*50:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*50:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*48:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*48:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*50:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*45:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__ib_a;
        QData/*45:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__ib_b;
        QData/*53:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__ib_c;
        QData/*45:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__pre_ovalue;
        QData/*45:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*45:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        QData/*53:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*48:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*48:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*52:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*52:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*48:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*52:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*52:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*50:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*50:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*52:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*45:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__ib_a;
        QData/*45:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__ib_b;
        QData/*53:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__ib_c;
        QData/*47:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__pre_ovalue;
        QData/*45:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*45:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        QData/*53:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*48:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*48:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*52:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*52:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*48:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*52:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*52:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*50:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*50:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*52:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*47:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__ib_a;
        QData/*47:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__ib_b;
        QData/*55:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__ib_c;
        QData/*47:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__pre_ovalue;
        QData/*47:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*47:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        QData/*55:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*50:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*50:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*54:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*54:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*50:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*54:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*54:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*52:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*52:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*54:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*47:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__ib_a;
        QData/*47:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__ib_b;
    };
    struct {
        QData/*55:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__ib_c;
        QData/*49:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__pre_ovalue;
        QData/*47:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*47:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        QData/*55:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*50:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*50:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*54:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*54:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*50:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*54:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*54:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*52:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*52:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*54:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*49:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__ib_a;
        QData/*49:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__ib_b;
        QData/*57:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__ib_c;
        QData/*49:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__pre_ovalue;
        QData/*49:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*49:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        QData/*57:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*52:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*52:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*56:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*56:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*52:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*56:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*56:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*54:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*54:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*56:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*51:0*/ dj__DOT__dj_0__DOT__left_ifft__DOT__stage_4__DOT__ob_a;
        VlUnpacked<QData/*39:0*/, 256> dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__cmem;
        VlUnpacked<IData/*31:0*/, 256> dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__imem;
        VlUnpacked<QData/*33:0*/, 256> dj__DOT__dj_0__DOT__left_fft__DOT__stage_512__DOT__omem;
        VlUnpacked<QData/*41:0*/, 128> dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__cmem;
        VlUnpacked<QData/*33:0*/, 128> dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__imem;
        VlUnpacked<QData/*35:0*/, 128> dj__DOT__dj_0__DOT__left_fft__DOT__stage_256__DOT__omem;
        VlUnpacked<QData/*43:0*/, 64> dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__cmem;
        VlUnpacked<QData/*35:0*/, 64> dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__imem;
        VlUnpacked<QData/*35:0*/, 64> dj__DOT__dj_0__DOT__left_fft__DOT__stage_128__DOT__omem;
        VlUnpacked<QData/*43:0*/, 32> dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__cmem;
        VlUnpacked<QData/*35:0*/, 32> dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__imem;
        VlUnpacked<QData/*37:0*/, 32> dj__DOT__dj_0__DOT__left_fft__DOT__stage_64__DOT__omem;
        VlUnpacked<QData/*45:0*/, 16> dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__cmem;
        VlUnpacked<QData/*37:0*/, 16> dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__imem;
        VlUnpacked<QData/*37:0*/, 16> dj__DOT__dj_0__DOT__left_fft__DOT__stage_32__DOT__omem;
        VlUnpacked<QData/*45:0*/, 8> dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__cmem;
        VlUnpacked<QData/*37:0*/, 8> dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__imem;
        VlUnpacked<QData/*39:0*/, 8> dj__DOT__dj_0__DOT__left_fft__DOT__stage_16__DOT__omem;
        VlUnpacked<QData/*47:0*/, 4> dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__cmem;
        VlUnpacked<QData/*39:0*/, 4> dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__imem;
        VlUnpacked<QData/*39:0*/, 4> dj__DOT__dj_0__DOT__left_fft__DOT__stage_8__DOT__omem;
        VlUnpacked<QData/*39:0*/, 2> dj__DOT__dj_0__DOT__left_fft__DOT__stage_4__DOT__imem;
        VlUnpacked<QData/*41:0*/, 2> dj__DOT__dj_0__DOT__left_fft__DOT__stage_4__DOT__omem;
        VlUnpacked<QData/*41:0*/, 1024> dj__DOT__dj_0__DOT__left_fft__DOT__revstage__DOT__brmem;
        VlUnpacked<QData/*49:0*/, 256> dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__cmem;
        VlUnpacked<QData/*41:0*/, 256> dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__imem;
        VlUnpacked<QData/*43:0*/, 256> dj__DOT__dj_0__DOT__left_ifft__DOT__stage_512__DOT__omem;
        VlUnpacked<QData/*51:0*/, 128> dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__cmem;
        VlUnpacked<QData/*43:0*/, 128> dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__imem;
        VlUnpacked<QData/*45:0*/, 128> dj__DOT__dj_0__DOT__left_ifft__DOT__stage_256__DOT__omem;
        VlUnpacked<QData/*53:0*/, 64> dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__cmem;
    };
    struct {
        VlUnpacked<QData/*45:0*/, 64> dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__imem;
        VlUnpacked<QData/*45:0*/, 64> dj__DOT__dj_0__DOT__left_ifft__DOT__stage_128__DOT__omem;
        VlUnpacked<QData/*53:0*/, 32> dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__cmem;
        VlUnpacked<QData/*45:0*/, 32> dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__imem;
        VlUnpacked<QData/*47:0*/, 32> dj__DOT__dj_0__DOT__left_ifft__DOT__stage_64__DOT__omem;
        VlUnpacked<QData/*55:0*/, 16> dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__cmem;
        VlUnpacked<QData/*47:0*/, 16> dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__imem;
        VlUnpacked<QData/*47:0*/, 16> dj__DOT__dj_0__DOT__left_ifft__DOT__stage_32__DOT__omem;
        VlUnpacked<QData/*55:0*/, 8> dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__cmem;
        VlUnpacked<QData/*47:0*/, 8> dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__imem;
        VlUnpacked<QData/*49:0*/, 8> dj__DOT__dj_0__DOT__left_ifft__DOT__stage_16__DOT__omem;
        VlUnpacked<QData/*57:0*/, 4> dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__cmem;
        VlUnpacked<QData/*49:0*/, 4> dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__imem;
        VlUnpacked<QData/*49:0*/, 4> dj__DOT__dj_0__DOT__left_ifft__DOT__stage_8__DOT__omem;
        VlUnpacked<QData/*49:0*/, 2> dj__DOT__dj_0__DOT__left_ifft__DOT__stage_4__DOT__imem;
        VlUnpacked<QData/*51:0*/, 2> dj__DOT__dj_0__DOT__left_ifft__DOT__stage_4__DOT__omem;
        VlUnpacked<QData/*51:0*/, 1024> dj__DOT__dj_0__DOT__left_ifft__DOT__revstage__DOT__brmem;
        VlUnpacked<SData/*15:0*/, 1024> dj__DOT__codec_left_fifo__DOT__mem;
        VlUnpacked<SData/*15:0*/, 1024> dj__DOT__codec_right_fifo__DOT__mem;
        VlUnpacked<SData/*15:0*/, 1024> dj__DOT__left_sc_fifo__DOT__mem;
        VlUnpacked<SData/*15:0*/, 1024> dj__DOT__right_sc_fifo__DOT__mem;
        VlUnpacked<CData/*0:0*/, 7> __Vm_traceActivity;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<3> __VactTriggered;
    VlTriggerVec<3> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vdj__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vdj___024root(Vdj__Syms* symsp, const char* v__name);
    ~Vdj___024root();
    VL_UNCOPYABLE(Vdj___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
