// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VDJ.h for the primary calling header

#ifndef VERILATED_VDJ___024ROOT_H_
#define VERILATED_VDJ___024ROOT_H_  // guard

#include "verilated.h"


class VDJ__Syms;

class alignas(VL_CACHE_LINE_BYTES) VDJ___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(reset,0,0);
        VL_IN8(write,0,0);
        VL_IN8(read,0,0);
        VL_IN8(stream_address,0,0);
        VL_OUT8(left_fifo_sink_valid,0,0);
        VL_IN8(left_fifo_source_valid,0,0);
        VL_IN8(left_fifo_almost_full,0,0);
        VL_IN8(left_fifo_almost_empty,0,0);
        VL_OUT8(left_fifo_interrupt,0,0);
        VL_OUT8(right_fifo_sink_valid,0,0);
        VL_IN8(right_fifo_source_valid,0,0);
        VL_IN8(right_fifo_almost_full,0,0);
        VL_IN8(right_fifo_almost_empty,0,0);
        VL_OUT8(right_fifo_interrupt,0,0);
        VL_OUT8(o_sync,0,0);
        CData/*0:0*/ DJ__DOT__fft_o_sync;
        CData/*0:0*/ DJ__DOT__ifft_i_reset;
        CData/*0:0*/ DJ__DOT__r_syncd;
        CData/*0:0*/ DJ__DOT__lpf_o_ce;
        CData/*0:0*/ DJ__DOT__lpf_o_sync;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__br_sync;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__w_s512;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__w_s256;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__w_s128;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__w_s64;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__w_s32;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__w_s16;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__w_s8;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__w_s4;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__w_s2;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__r_br_started;
        CData/*0:0*/ DJ__DOT__left_fft__DOT____Vcellinp__revstage__i_ce;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__wait_for_sync;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__ib_sync;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__b_started;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__ob_sync;
        CData/*7:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__nxt_oaddr;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__wait_for_sync;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__ib_sync;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__b_started;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__ob_sync;
        CData/*7:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__iaddr;
        CData/*7:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__oaddr;
        CData/*6:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__nxt_oaddr;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__wait_for_sync;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__ib_sync;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__b_started;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__ob_sync;
        CData/*6:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__iaddr;
        CData/*6:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__oaddr;
        CData/*5:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__nxt_oaddr;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__wait_for_sync;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__ib_sync;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__b_started;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__ob_sync;
        CData/*5:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__iaddr;
        CData/*5:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__oaddr;
    };
    struct {
        CData/*4:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__nxt_oaddr;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__wait_for_sync;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__ib_sync;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__b_started;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__ob_sync;
        CData/*4:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__iaddr;
        CData/*4:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__oaddr;
        CData/*3:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__nxt_oaddr;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__wait_for_sync;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__ib_sync;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__b_started;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__ob_sync;
        CData/*3:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__iaddr;
        CData/*3:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__oaddr;
        CData/*2:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__nxt_oaddr;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__wait_for_sync;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__ib_sync;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__b_started;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__ob_sync;
        CData/*2:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__iaddr;
        CData/*2:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__oaddr;
        CData/*1:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__nxt_oaddr;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_4__DOT__wait_for_sync;
        CData/*2:0*/ DJ__DOT__left_fft__DOT__stage_4__DOT__pipeline;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_2__DOT__wait_for_sync;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__stage_2__DOT__stage;
        CData/*1:0*/ DJ__DOT__left_fft__DOT__stage_2__DOT__sync_pipe;
        CData/*0:0*/ DJ__DOT__left_fft__DOT__revstage__DOT__in_reset;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__br_sync;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__w_s512;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__w_s256;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__w_s128;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__w_s64;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__w_s32;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__w_s16;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__w_s8;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__w_s4;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__w_s2;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__r_br_started;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT____Vcellinp__revstage__i_ce;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__wait_for_sync;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__ib_sync;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__b_started;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__ob_sync;
        CData/*7:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__nxt_oaddr;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__wait_for_sync;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__ib_sync;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__b_started;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__ob_sync;
        CData/*7:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__iaddr;
        CData/*7:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__oaddr;
        CData/*6:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__nxt_oaddr;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
    };
    struct {
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__wait_for_sync;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__ib_sync;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__b_started;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__ob_sync;
        CData/*6:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__iaddr;
        CData/*6:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__oaddr;
        CData/*5:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__nxt_oaddr;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__wait_for_sync;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__ib_sync;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__b_started;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__ob_sync;
        CData/*5:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__iaddr;
        CData/*5:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__oaddr;
        CData/*4:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__nxt_oaddr;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__wait_for_sync;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__ib_sync;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__b_started;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__ob_sync;
        CData/*4:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__iaddr;
        CData/*4:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__oaddr;
        CData/*3:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__nxt_oaddr;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__wait_for_sync;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__ib_sync;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__b_started;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__ob_sync;
        CData/*3:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__iaddr;
        CData/*3:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__oaddr;
        CData/*2:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__nxt_oaddr;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__wait_for_sync;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__ib_sync;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__b_started;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__ob_sync;
        CData/*2:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__iaddr;
        CData/*2:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__oaddr;
        CData/*1:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__nxt_oaddr;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_4__DOT__wait_for_sync;
        CData/*2:0*/ DJ__DOT__left_ifft__DOT__stage_4__DOT__pipeline;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_2__DOT__wait_for_sync;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__stage_2__DOT__stage;
        CData/*1:0*/ DJ__DOT__left_ifft__DOT__stage_2__DOT__sync_pipe;
        CData/*0:0*/ DJ__DOT__left_ifft__DOT__revstage__DOT__in_reset;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __VactContinue;
        VL_IN16(writedata,15,0);
        VL_OUT16(left_fifo_sink_stream,15,0);
        VL_IN16(left_fifo_source_stream,15,0);
        VL_OUT16(right_fifo_sink_stream,15,0);
        VL_IN16(right_fifo_source_stream,15,0);
        VL_OUT16(readdata,15,0);
        SData/*8:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__iaddr;
        SData/*8:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__oaddr;
        SData/*8:0*/ DJ__DOT__left_fft__DOT__stage_4__DOT__iaddr;
    };
    struct {
        SData/*9:0*/ DJ__DOT__left_fft__DOT__revstage__DOT__wraddr;
        SData/*9:0*/ DJ__DOT__left_lpf__DOT__bin_idx;
        SData/*8:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__iaddr;
        SData/*8:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__oaddr;
        SData/*8:0*/ DJ__DOT__left_ifft__DOT__stage_4__DOT__iaddr;
        SData/*9:0*/ DJ__DOT__left_ifft__DOT__revstage__DOT__wraddr;
        IData/*31:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__ib_a;
        IData/*31:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__ib_b;
        IData/*31:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        IData/*31:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        IData/*19:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*19:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*16:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*16:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*16:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*16:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*16:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*16:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*16:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*16:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*19:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*19:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*16:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*16:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*20:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*17:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*20:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*20:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*17:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*17:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*17:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*17:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*17:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*17:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*17:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*17:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*20:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*20:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*17:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*17:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*21:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*18:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*21:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*21:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*18:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*18:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*18:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*18:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*17:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*17:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*17:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*17:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*21:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*21:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*18:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*18:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*22:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*19:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*21:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*21:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*18:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*18:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*18:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*18:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
    };
    struct {
        IData/*18:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*18:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*18:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*18:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*21:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*21:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*18:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*18:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*22:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*19:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*22:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*22:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*19:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*19:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*19:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*19:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*18:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*18:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*18:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*18:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*22:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*22:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*19:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*19:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*23:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*20:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*22:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*22:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*19:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*19:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*19:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*19:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*19:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*19:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*19:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*19:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*22:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*22:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*19:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*19:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*23:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*20:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*23:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*23:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*20:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*20:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*20:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*20:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*19:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*19:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*19:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*19:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*23:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*23:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*20:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*20:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*24:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*21:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*20:0*/ DJ__DOT__left_fft__DOT__stage_4__DOT__sum_r;
        IData/*20:0*/ DJ__DOT__left_fft__DOT__stage_4__DOT__sum_i;
        IData/*20:0*/ DJ__DOT__left_fft__DOT__stage_4__DOT__diff_r;
        IData/*20:0*/ DJ__DOT__left_fft__DOT__stage_4__DOT__diff_i;
        IData/*20:0*/ DJ__DOT__left_fft__DOT__stage_4__DOT__ob_b_r;
        IData/*20:0*/ DJ__DOT__left_fft__DOT__stage_4__DOT__ob_b_i;
    };
    struct {
        IData/*20:0*/ DJ__DOT__left_fft__DOT__stage_4__DOT__rnd_sum_r;
        IData/*20:0*/ DJ__DOT__left_fft__DOT__stage_4__DOT__rnd_sum_i;
        IData/*20:0*/ DJ__DOT__left_fft__DOT__stage_4__DOT__rnd_diff_r;
        IData/*20:0*/ DJ__DOT__left_fft__DOT__stage_4__DOT__rnd_diff_i;
        IData/*20:0*/ DJ__DOT__left_fft__DOT__stage_2__DOT__m_r;
        IData/*20:0*/ DJ__DOT__left_fft__DOT__stage_2__DOT__m_i;
        IData/*21:0*/ DJ__DOT__left_fft__DOT__stage_2__DOT__rnd_r;
        IData/*21:0*/ DJ__DOT__left_fft__DOT__stage_2__DOT__rnd_i;
        IData/*21:0*/ DJ__DOT__left_fft__DOT__stage_2__DOT__sto_r;
        IData/*21:0*/ DJ__DOT__left_fft__DOT__stage_2__DOT__sto_i;
        IData/*20:0*/ DJ__DOT__left_fft__DOT__stage_2__DOT__o_r;
        IData/*20:0*/ DJ__DOT__left_fft__DOT__stage_2__DOT__o_i;
        IData/*24:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*24:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*21:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*21:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*21:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*21:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*21:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*21:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*21:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*21:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*24:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*24:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*21:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*21:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*25:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*22:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*25:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*25:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*22:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*22:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*22:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*22:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*22:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*22:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*22:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*22:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*25:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*25:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*22:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*22:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*26:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*23:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*26:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*26:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*23:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*23:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*23:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*23:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*22:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*22:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*22:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*22:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*26:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*26:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*23:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*23:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*27:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*24:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*26:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*26:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*23:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*23:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
    };
    struct {
        IData/*23:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*23:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*23:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*23:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*23:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*23:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*26:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*26:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*23:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*23:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*27:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*24:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*27:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*27:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*24:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*24:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*24:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*24:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*23:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*23:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*23:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*23:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*27:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*27:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*24:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*24:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*28:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*25:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*27:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*27:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*24:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*24:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*24:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*24:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*24:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*24:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*24:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*24:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*27:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*27:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*24:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*24:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*28:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*25:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*28:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*28:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*25:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*25:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*25:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*25:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*24:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*24:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*24:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*24:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*28:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*28:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*25:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*25:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*29:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*26:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*25:0*/ DJ__DOT__left_ifft__DOT__stage_4__DOT__sum_r;
        IData/*25:0*/ DJ__DOT__left_ifft__DOT__stage_4__DOT__sum_i;
        IData/*25:0*/ DJ__DOT__left_ifft__DOT__stage_4__DOT__diff_r;
        IData/*25:0*/ DJ__DOT__left_ifft__DOT__stage_4__DOT__diff_i;
    };
    struct {
        IData/*25:0*/ DJ__DOT__left_ifft__DOT__stage_4__DOT__ob_b_r;
        IData/*25:0*/ DJ__DOT__left_ifft__DOT__stage_4__DOT__ob_b_i;
        IData/*25:0*/ DJ__DOT__left_ifft__DOT__stage_4__DOT__rnd_sum_r;
        IData/*25:0*/ DJ__DOT__left_ifft__DOT__stage_4__DOT__rnd_sum_i;
        IData/*25:0*/ DJ__DOT__left_ifft__DOT__stage_4__DOT__rnd_diff_r;
        IData/*25:0*/ DJ__DOT__left_ifft__DOT__stage_4__DOT__rnd_diff_i;
        IData/*25:0*/ DJ__DOT__left_ifft__DOT__stage_2__DOT__m_r;
        IData/*25:0*/ DJ__DOT__left_ifft__DOT__stage_2__DOT__m_i;
        IData/*26:0*/ DJ__DOT__left_ifft__DOT__stage_2__DOT__rnd_r;
        IData/*26:0*/ DJ__DOT__left_ifft__DOT__stage_2__DOT__rnd_i;
        IData/*26:0*/ DJ__DOT__left_ifft__DOT__stage_2__DOT__sto_r;
        IData/*26:0*/ DJ__DOT__left_ifft__DOT__stage_2__DOT__sto_i;
        IData/*25:0*/ DJ__DOT__left_ifft__DOT__stage_2__DOT__o_r;
        IData/*25:0*/ DJ__DOT__left_ifft__DOT__stage_2__DOT__o_i;
        IData/*31:0*/ __VactIterCount;
        VL_OUT64(o_result,51,0);
        QData/*41:0*/ DJ__DOT__fft_o_result;
        QData/*41:0*/ DJ__DOT__lpf_o_sample;
        QData/*41:0*/ DJ__DOT__left_fft__DOT__br_result;
        QData/*33:0*/ DJ__DOT__left_fft__DOT__w_d512;
        QData/*35:0*/ DJ__DOT__left_fft__DOT__w_d256;
        QData/*35:0*/ DJ__DOT__left_fft__DOT__w_d128;
        QData/*37:0*/ DJ__DOT__left_fft__DOT__w_d64;
        QData/*37:0*/ DJ__DOT__left_fft__DOT__w_d32;
        QData/*39:0*/ DJ__DOT__left_fft__DOT__w_d16;
        QData/*39:0*/ DJ__DOT__left_fft__DOT__w_d8;
        QData/*41:0*/ DJ__DOT__left_fft__DOT__w_d4;
        QData/*39:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__ib_c;
        QData/*33:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__pre_ovalue;
        QData/*39:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*34:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*34:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*38:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*38:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*34:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*38:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*38:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*36:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*36:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*38:0*/ DJ__DOT__left_fft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*33:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__ib_a;
        QData/*33:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__ib_b;
        QData/*41:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__ib_c;
        QData/*35:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__pre_ovalue;
        QData/*33:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*33:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        QData/*41:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*36:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*36:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*40:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*40:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*36:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*40:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*40:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*38:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*38:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*40:0*/ DJ__DOT__left_fft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*35:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__ib_a;
        QData/*35:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__ib_b;
        QData/*43:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__ib_c;
        QData/*35:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__pre_ovalue;
        QData/*35:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*35:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        QData/*43:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
    };
    struct {
        QData/*38:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*38:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*42:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*42:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*38:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*42:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*42:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*40:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*40:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*42:0*/ DJ__DOT__left_fft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*35:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__ib_a;
        QData/*35:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__ib_b;
        QData/*43:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__ib_c;
        QData/*37:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__pre_ovalue;
        QData/*35:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*35:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        QData/*43:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*38:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*38:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*42:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*42:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*38:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*42:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*42:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*40:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*40:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*42:0*/ DJ__DOT__left_fft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*37:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__ib_a;
        QData/*37:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__ib_b;
        QData/*45:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__ib_c;
        QData/*37:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__pre_ovalue;
        QData/*37:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*37:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        QData/*45:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*40:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*40:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*44:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*44:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*40:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*44:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*44:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*42:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*42:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*44:0*/ DJ__DOT__left_fft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*37:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__ib_a;
        QData/*37:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__ib_b;
        QData/*45:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__ib_c;
        QData/*39:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__pre_ovalue;
        QData/*37:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*37:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        QData/*45:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*40:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*40:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*44:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*44:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*40:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*44:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*44:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*42:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*42:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*44:0*/ DJ__DOT__left_fft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*39:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__ib_a;
        QData/*39:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__ib_b;
        QData/*47:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__ib_c;
    };
    struct {
        QData/*39:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__pre_ovalue;
        QData/*39:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*39:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        QData/*47:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*42:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*42:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*46:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*46:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*42:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*46:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*46:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*44:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*44:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*46:0*/ DJ__DOT__left_fft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*41:0*/ DJ__DOT__left_fft__DOT__stage_4__DOT__ob_a;
        QData/*51:0*/ DJ__DOT__left_ifft__DOT__br_result;
        QData/*43:0*/ DJ__DOT__left_ifft__DOT__w_d512;
        QData/*45:0*/ DJ__DOT__left_ifft__DOT__w_d256;
        QData/*45:0*/ DJ__DOT__left_ifft__DOT__w_d128;
        QData/*47:0*/ DJ__DOT__left_ifft__DOT__w_d64;
        QData/*47:0*/ DJ__DOT__left_ifft__DOT__w_d32;
        QData/*49:0*/ DJ__DOT__left_ifft__DOT__w_d16;
        QData/*49:0*/ DJ__DOT__left_ifft__DOT__w_d8;
        QData/*51:0*/ DJ__DOT__left_ifft__DOT__w_d4;
        QData/*41:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__ib_a;
        QData/*41:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__ib_b;
        QData/*49:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__ib_c;
        QData/*43:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__pre_ovalue;
        QData/*41:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*41:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        QData/*49:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*44:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*44:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*48:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*48:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*44:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*48:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*48:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*46:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*46:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*48:0*/ DJ__DOT__left_ifft__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*43:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__ib_a;
        QData/*43:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__ib_b;
        QData/*51:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__ib_c;
        QData/*45:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__pre_ovalue;
        QData/*43:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*43:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        QData/*51:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*46:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*46:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*50:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*50:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*46:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*50:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*50:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*48:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*48:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*50:0*/ DJ__DOT__left_ifft__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*45:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__ib_a;
        QData/*45:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__ib_b;
        QData/*53:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__ib_c;
        QData/*45:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__pre_ovalue;
        QData/*45:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*45:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_right;
    };
    struct {
        QData/*53:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*48:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*48:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*52:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*52:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*48:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*52:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*52:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*50:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*50:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*52:0*/ DJ__DOT__left_ifft__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*45:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__ib_a;
        QData/*45:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__ib_b;
        QData/*53:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__ib_c;
        QData/*47:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__pre_ovalue;
        QData/*45:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*45:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        QData/*53:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*48:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*48:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*52:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*52:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*48:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*52:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*52:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*50:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*50:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*52:0*/ DJ__DOT__left_ifft__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*47:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__ib_a;
        QData/*47:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__ib_b;
        QData/*55:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__ib_c;
        QData/*47:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__pre_ovalue;
        QData/*47:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*47:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        QData/*55:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*50:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*50:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*54:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*54:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*50:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*54:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*54:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*52:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*52:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*54:0*/ DJ__DOT__left_ifft__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*47:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__ib_a;
        QData/*47:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__ib_b;
        QData/*55:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__ib_c;
        QData/*49:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__pre_ovalue;
        QData/*47:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*47:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        QData/*55:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*50:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*50:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*54:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*54:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*50:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*54:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*54:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*52:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*52:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*54:0*/ DJ__DOT__left_ifft__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*49:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__ib_a;
        QData/*49:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__ib_b;
    };
    struct {
        QData/*57:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__ib_c;
        QData/*49:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__pre_ovalue;
        QData/*49:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*49:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        QData/*57:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*52:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*52:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*56:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*56:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*52:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*56:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*56:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*54:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*54:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*56:0*/ DJ__DOT__left_ifft__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*51:0*/ DJ__DOT__left_ifft__DOT__stage_4__DOT__ob_a;
        VlUnpacked<QData/*39:0*/, 256> DJ__DOT__left_fft__DOT__stage_512__DOT__cmem;
        VlUnpacked<IData/*31:0*/, 256> DJ__DOT__left_fft__DOT__stage_512__DOT__imem;
        VlUnpacked<QData/*33:0*/, 256> DJ__DOT__left_fft__DOT__stage_512__DOT__omem;
        VlUnpacked<QData/*41:0*/, 128> DJ__DOT__left_fft__DOT__stage_256__DOT__cmem;
        VlUnpacked<QData/*33:0*/, 128> DJ__DOT__left_fft__DOT__stage_256__DOT__imem;
        VlUnpacked<QData/*35:0*/, 128> DJ__DOT__left_fft__DOT__stage_256__DOT__omem;
        VlUnpacked<QData/*43:0*/, 64> DJ__DOT__left_fft__DOT__stage_128__DOT__cmem;
        VlUnpacked<QData/*35:0*/, 64> DJ__DOT__left_fft__DOT__stage_128__DOT__imem;
        VlUnpacked<QData/*35:0*/, 64> DJ__DOT__left_fft__DOT__stage_128__DOT__omem;
        VlUnpacked<QData/*43:0*/, 32> DJ__DOT__left_fft__DOT__stage_64__DOT__cmem;
        VlUnpacked<QData/*35:0*/, 32> DJ__DOT__left_fft__DOT__stage_64__DOT__imem;
        VlUnpacked<QData/*37:0*/, 32> DJ__DOT__left_fft__DOT__stage_64__DOT__omem;
        VlUnpacked<QData/*45:0*/, 16> DJ__DOT__left_fft__DOT__stage_32__DOT__cmem;
        VlUnpacked<QData/*37:0*/, 16> DJ__DOT__left_fft__DOT__stage_32__DOT__imem;
        VlUnpacked<QData/*37:0*/, 16> DJ__DOT__left_fft__DOT__stage_32__DOT__omem;
        VlUnpacked<QData/*45:0*/, 8> DJ__DOT__left_fft__DOT__stage_16__DOT__cmem;
        VlUnpacked<QData/*37:0*/, 8> DJ__DOT__left_fft__DOT__stage_16__DOT__imem;
        VlUnpacked<QData/*39:0*/, 8> DJ__DOT__left_fft__DOT__stage_16__DOT__omem;
        VlUnpacked<QData/*47:0*/, 4> DJ__DOT__left_fft__DOT__stage_8__DOT__cmem;
        VlUnpacked<QData/*39:0*/, 4> DJ__DOT__left_fft__DOT__stage_8__DOT__imem;
        VlUnpacked<QData/*39:0*/, 4> DJ__DOT__left_fft__DOT__stage_8__DOT__omem;
        VlUnpacked<QData/*39:0*/, 2> DJ__DOT__left_fft__DOT__stage_4__DOT__imem;
        VlUnpacked<QData/*41:0*/, 2> DJ__DOT__left_fft__DOT__stage_4__DOT__omem;
        VlUnpacked<QData/*41:0*/, 1024> DJ__DOT__left_fft__DOT__revstage__DOT__brmem;
        VlUnpacked<QData/*49:0*/, 256> DJ__DOT__left_ifft__DOT__stage_512__DOT__cmem;
        VlUnpacked<QData/*41:0*/, 256> DJ__DOT__left_ifft__DOT__stage_512__DOT__imem;
        VlUnpacked<QData/*43:0*/, 256> DJ__DOT__left_ifft__DOT__stage_512__DOT__omem;
        VlUnpacked<QData/*51:0*/, 128> DJ__DOT__left_ifft__DOT__stage_256__DOT__cmem;
        VlUnpacked<QData/*43:0*/, 128> DJ__DOT__left_ifft__DOT__stage_256__DOT__imem;
        VlUnpacked<QData/*45:0*/, 128> DJ__DOT__left_ifft__DOT__stage_256__DOT__omem;
        VlUnpacked<QData/*53:0*/, 64> DJ__DOT__left_ifft__DOT__stage_128__DOT__cmem;
        VlUnpacked<QData/*45:0*/, 64> DJ__DOT__left_ifft__DOT__stage_128__DOT__imem;
        VlUnpacked<QData/*45:0*/, 64> DJ__DOT__left_ifft__DOT__stage_128__DOT__omem;
        VlUnpacked<QData/*53:0*/, 32> DJ__DOT__left_ifft__DOT__stage_64__DOT__cmem;
        VlUnpacked<QData/*45:0*/, 32> DJ__DOT__left_ifft__DOT__stage_64__DOT__imem;
        VlUnpacked<QData/*47:0*/, 32> DJ__DOT__left_ifft__DOT__stage_64__DOT__omem;
        VlUnpacked<QData/*55:0*/, 16> DJ__DOT__left_ifft__DOT__stage_32__DOT__cmem;
        VlUnpacked<QData/*47:0*/, 16> DJ__DOT__left_ifft__DOT__stage_32__DOT__imem;
        VlUnpacked<QData/*47:0*/, 16> DJ__DOT__left_ifft__DOT__stage_32__DOT__omem;
        VlUnpacked<QData/*55:0*/, 8> DJ__DOT__left_ifft__DOT__stage_16__DOT__cmem;
        VlUnpacked<QData/*47:0*/, 8> DJ__DOT__left_ifft__DOT__stage_16__DOT__imem;
        VlUnpacked<QData/*49:0*/, 8> DJ__DOT__left_ifft__DOT__stage_16__DOT__omem;
        VlUnpacked<QData/*57:0*/, 4> DJ__DOT__left_ifft__DOT__stage_8__DOT__cmem;
        VlUnpacked<QData/*49:0*/, 4> DJ__DOT__left_ifft__DOT__stage_8__DOT__imem;
        VlUnpacked<QData/*49:0*/, 4> DJ__DOT__left_ifft__DOT__stage_8__DOT__omem;
        VlUnpacked<QData/*49:0*/, 2> DJ__DOT__left_ifft__DOT__stage_4__DOT__imem;
        VlUnpacked<QData/*51:0*/, 2> DJ__DOT__left_ifft__DOT__stage_4__DOT__omem;
        VlUnpacked<QData/*51:0*/, 1024> DJ__DOT__left_ifft__DOT__revstage__DOT__brmem;
    };
    struct {
        VlUnpacked<CData/*0:0*/, 2> __Vm_traceActivity;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<1> __VactTriggered;
    VlTriggerVec<1> __VnbaTriggered;

    // INTERNAL VARIABLES
    VDJ__Syms* const vlSymsp;

    // CONSTRUCTORS
    VDJ___024root(VDJ__Syms* symsp, const char* v__name);
    ~VDJ___024root();
    VL_UNCOPYABLE(VDJ___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
