// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vfftmain.h for the primary calling header

#ifndef VERILATED_VFFTMAIN___024ROOT_H_
#define VERILATED_VFFTMAIN___024ROOT_H_  // guard

#include "verilated.h"


class Vfftmain__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vfftmain___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(i_clk,0,0);
        VL_IN8(i_reset,0,0);
        VL_IN8(i_ce,0,0);
        VL_OUT8(o_sync,0,0);
        CData/*0:0*/ fftmain__DOT__br_sync;
        CData/*0:0*/ fftmain__DOT__w_s512;
        CData/*0:0*/ fftmain__DOT__w_s256;
        CData/*0:0*/ fftmain__DOT__w_s128;
        CData/*0:0*/ fftmain__DOT__w_s64;
        CData/*0:0*/ fftmain__DOT__w_s32;
        CData/*0:0*/ fftmain__DOT__w_s16;
        CData/*0:0*/ fftmain__DOT__w_s8;
        CData/*0:0*/ fftmain__DOT__w_s4;
        CData/*0:0*/ fftmain__DOT__w_s2;
        CData/*0:0*/ fftmain__DOT__r_br_started;
        CData/*0:0*/ fftmain__DOT____Vcellinp__revstage__i_ce;
        CData/*0:0*/ fftmain__DOT__stage_512__DOT__wait_for_sync;
        CData/*0:0*/ fftmain__DOT__stage_512__DOT__ib_sync;
        CData/*0:0*/ fftmain__DOT__stage_512__DOT__b_started;
        CData/*0:0*/ fftmain__DOT__stage_512__DOT__ob_sync;
        CData/*7:0*/ fftmain__DOT__stage_512__DOT__nxt_oaddr;
        CData/*0:0*/ fftmain__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ fftmain__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ fftmain__DOT__stage_256__DOT__wait_for_sync;
        CData/*0:0*/ fftmain__DOT__stage_256__DOT__ib_sync;
        CData/*0:0*/ fftmain__DOT__stage_256__DOT__b_started;
        CData/*0:0*/ fftmain__DOT__stage_256__DOT__ob_sync;
        CData/*7:0*/ fftmain__DOT__stage_256__DOT__iaddr;
        CData/*7:0*/ fftmain__DOT__stage_256__DOT__oaddr;
        CData/*6:0*/ fftmain__DOT__stage_256__DOT__nxt_oaddr;
        CData/*0:0*/ fftmain__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ fftmain__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ fftmain__DOT__stage_128__DOT__wait_for_sync;
        CData/*0:0*/ fftmain__DOT__stage_128__DOT__ib_sync;
        CData/*0:0*/ fftmain__DOT__stage_128__DOT__b_started;
        CData/*0:0*/ fftmain__DOT__stage_128__DOT__ob_sync;
        CData/*6:0*/ fftmain__DOT__stage_128__DOT__iaddr;
        CData/*6:0*/ fftmain__DOT__stage_128__DOT__oaddr;
        CData/*5:0*/ fftmain__DOT__stage_128__DOT__nxt_oaddr;
        CData/*0:0*/ fftmain__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ fftmain__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ fftmain__DOT__stage_64__DOT__wait_for_sync;
        CData/*0:0*/ fftmain__DOT__stage_64__DOT__ib_sync;
        CData/*0:0*/ fftmain__DOT__stage_64__DOT__b_started;
        CData/*0:0*/ fftmain__DOT__stage_64__DOT__ob_sync;
        CData/*5:0*/ fftmain__DOT__stage_64__DOT__iaddr;
        CData/*5:0*/ fftmain__DOT__stage_64__DOT__oaddr;
        CData/*4:0*/ fftmain__DOT__stage_64__DOT__nxt_oaddr;
        CData/*0:0*/ fftmain__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ fftmain__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ fftmain__DOT__stage_32__DOT__wait_for_sync;
        CData/*0:0*/ fftmain__DOT__stage_32__DOT__ib_sync;
        CData/*0:0*/ fftmain__DOT__stage_32__DOT__b_started;
        CData/*0:0*/ fftmain__DOT__stage_32__DOT__ob_sync;
        CData/*4:0*/ fftmain__DOT__stage_32__DOT__iaddr;
        CData/*4:0*/ fftmain__DOT__stage_32__DOT__oaddr;
        CData/*3:0*/ fftmain__DOT__stage_32__DOT__nxt_oaddr;
        CData/*0:0*/ fftmain__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ fftmain__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ fftmain__DOT__stage_16__DOT__wait_for_sync;
        CData/*0:0*/ fftmain__DOT__stage_16__DOT__ib_sync;
        CData/*0:0*/ fftmain__DOT__stage_16__DOT__b_started;
        CData/*0:0*/ fftmain__DOT__stage_16__DOT__ob_sync;
        CData/*3:0*/ fftmain__DOT__stage_16__DOT__iaddr;
    };
    struct {
        CData/*3:0*/ fftmain__DOT__stage_16__DOT__oaddr;
        CData/*2:0*/ fftmain__DOT__stage_16__DOT__nxt_oaddr;
        CData/*0:0*/ fftmain__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ fftmain__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ fftmain__DOT__stage_8__DOT__wait_for_sync;
        CData/*0:0*/ fftmain__DOT__stage_8__DOT__ib_sync;
        CData/*0:0*/ fftmain__DOT__stage_8__DOT__b_started;
        CData/*0:0*/ fftmain__DOT__stage_8__DOT__ob_sync;
        CData/*2:0*/ fftmain__DOT__stage_8__DOT__iaddr;
        CData/*2:0*/ fftmain__DOT__stage_8__DOT__oaddr;
        CData/*1:0*/ fftmain__DOT__stage_8__DOT__nxt_oaddr;
        CData/*0:0*/ fftmain__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_aux;
        CData/*0:0*/ fftmain__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_aux_2;
        CData/*0:0*/ fftmain__DOT__stage_4__DOT__wait_for_sync;
        CData/*2:0*/ fftmain__DOT__stage_4__DOT__pipeline;
        CData/*0:0*/ fftmain__DOT__stage_2__DOT__wait_for_sync;
        CData/*0:0*/ fftmain__DOT__stage_2__DOT__stage;
        CData/*1:0*/ fftmain__DOT__stage_2__DOT__sync_pipe;
        CData/*0:0*/ fftmain__DOT__revstage__DOT__in_reset;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__i_clk__0;
        CData/*0:0*/ __VactContinue;
        SData/*8:0*/ fftmain__DOT__stage_512__DOT__iaddr;
        SData/*8:0*/ fftmain__DOT__stage_512__DOT__oaddr;
        SData/*8:0*/ fftmain__DOT__stage_4__DOT__iaddr;
        SData/*9:0*/ fftmain__DOT__revstage__DOT__wraddr;
        VL_IN(i_sample,31,0);
        IData/*31:0*/ fftmain__DOT__stage_512__DOT__ib_a;
        IData/*31:0*/ fftmain__DOT__stage_512__DOT__ib_b;
        IData/*31:0*/ fftmain__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        IData/*31:0*/ fftmain__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        IData/*19:0*/ fftmain__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*19:0*/ fftmain__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*16:0*/ fftmain__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*16:0*/ fftmain__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*16:0*/ fftmain__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*16:0*/ fftmain__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*16:0*/ fftmain__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*16:0*/ fftmain__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*16:0*/ fftmain__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*16:0*/ fftmain__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*19:0*/ fftmain__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*19:0*/ fftmain__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*16:0*/ fftmain__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*16:0*/ fftmain__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*20:0*/ fftmain__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*17:0*/ fftmain__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*20:0*/ fftmain__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*20:0*/ fftmain__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*17:0*/ fftmain__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*17:0*/ fftmain__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*17:0*/ fftmain__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*17:0*/ fftmain__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*17:0*/ fftmain__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*17:0*/ fftmain__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*17:0*/ fftmain__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*17:0*/ fftmain__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*20:0*/ fftmain__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*20:0*/ fftmain__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*17:0*/ fftmain__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*17:0*/ fftmain__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*21:0*/ fftmain__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*18:0*/ fftmain__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
    };
    struct {
        IData/*21:0*/ fftmain__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*21:0*/ fftmain__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*18:0*/ fftmain__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*18:0*/ fftmain__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*18:0*/ fftmain__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*18:0*/ fftmain__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*17:0*/ fftmain__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*17:0*/ fftmain__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*17:0*/ fftmain__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*17:0*/ fftmain__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*21:0*/ fftmain__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*21:0*/ fftmain__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*18:0*/ fftmain__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*18:0*/ fftmain__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*22:0*/ fftmain__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*19:0*/ fftmain__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*21:0*/ fftmain__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*21:0*/ fftmain__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*18:0*/ fftmain__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*18:0*/ fftmain__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*18:0*/ fftmain__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*18:0*/ fftmain__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*18:0*/ fftmain__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*18:0*/ fftmain__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*18:0*/ fftmain__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*18:0*/ fftmain__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*21:0*/ fftmain__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*21:0*/ fftmain__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*18:0*/ fftmain__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*18:0*/ fftmain__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*22:0*/ fftmain__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*19:0*/ fftmain__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*22:0*/ fftmain__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*22:0*/ fftmain__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*19:0*/ fftmain__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*19:0*/ fftmain__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*19:0*/ fftmain__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*19:0*/ fftmain__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*18:0*/ fftmain__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*18:0*/ fftmain__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*18:0*/ fftmain__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*18:0*/ fftmain__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*22:0*/ fftmain__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*22:0*/ fftmain__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*19:0*/ fftmain__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*19:0*/ fftmain__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*23:0*/ fftmain__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*20:0*/ fftmain__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*22:0*/ fftmain__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*22:0*/ fftmain__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*19:0*/ fftmain__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*19:0*/ fftmain__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*19:0*/ fftmain__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*19:0*/ fftmain__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*19:0*/ fftmain__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*19:0*/ fftmain__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*19:0*/ fftmain__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*19:0*/ fftmain__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*22:0*/ fftmain__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*22:0*/ fftmain__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*19:0*/ fftmain__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*19:0*/ fftmain__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*23:0*/ fftmain__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*20:0*/ fftmain__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
    };
    struct {
        IData/*23:0*/ fftmain__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_r;
        IData/*23:0*/ fftmain__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__ir_coef_i;
        IData/*20:0*/ fftmain__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_sum_r;
        IData/*20:0*/ fftmain__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_sum_i;
        IData/*20:0*/ fftmain__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_dif_r;
        IData/*20:0*/ fftmain__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_dif_i;
        IData/*19:0*/ fftmain__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_r;
        IData/*19:0*/ fftmain__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__rnd_left_i;
        IData/*19:0*/ fftmain__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_r;
        IData/*19:0*/ fftmain__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__rnd_right_i;
        IData/*23:0*/ fftmain__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1c_in;
        IData/*23:0*/ fftmain__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2c_in;
        IData/*20:0*/ fftmain__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p1d_in;
        IData/*20:0*/ fftmain__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p2d_in;
        IData/*24:0*/ fftmain__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3c_in;
        IData/*21:0*/ fftmain__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__p3d_in;
        IData/*20:0*/ fftmain__DOT__stage_4__DOT__sum_r;
        IData/*20:0*/ fftmain__DOT__stage_4__DOT__sum_i;
        IData/*20:0*/ fftmain__DOT__stage_4__DOT__diff_r;
        IData/*20:0*/ fftmain__DOT__stage_4__DOT__diff_i;
        IData/*20:0*/ fftmain__DOT__stage_4__DOT__ob_b_r;
        IData/*20:0*/ fftmain__DOT__stage_4__DOT__ob_b_i;
        IData/*20:0*/ fftmain__DOT__stage_4__DOT__rnd_sum_r;
        IData/*20:0*/ fftmain__DOT__stage_4__DOT__rnd_sum_i;
        IData/*20:0*/ fftmain__DOT__stage_4__DOT__rnd_diff_r;
        IData/*20:0*/ fftmain__DOT__stage_4__DOT__rnd_diff_i;
        IData/*20:0*/ fftmain__DOT__stage_2__DOT__m_r;
        IData/*20:0*/ fftmain__DOT__stage_2__DOT__m_i;
        IData/*21:0*/ fftmain__DOT__stage_2__DOT__rnd_r;
        IData/*21:0*/ fftmain__DOT__stage_2__DOT__rnd_i;
        IData/*21:0*/ fftmain__DOT__stage_2__DOT__sto_r;
        IData/*21:0*/ fftmain__DOT__stage_2__DOT__sto_i;
        IData/*20:0*/ fftmain__DOT__stage_2__DOT__o_r;
        IData/*20:0*/ fftmain__DOT__stage_2__DOT__o_i;
        IData/*31:0*/ __VactIterCount;
        VL_OUT64(o_result,41,0);
        QData/*41:0*/ fftmain__DOT__br_result;
        QData/*33:0*/ fftmain__DOT__w_d512;
        QData/*35:0*/ fftmain__DOT__w_d256;
        QData/*35:0*/ fftmain__DOT__w_d128;
        QData/*37:0*/ fftmain__DOT__w_d64;
        QData/*37:0*/ fftmain__DOT__w_d32;
        QData/*39:0*/ fftmain__DOT__w_d16;
        QData/*39:0*/ fftmain__DOT__w_d8;
        QData/*41:0*/ fftmain__DOT__w_d4;
        QData/*39:0*/ fftmain__DOT__stage_512__DOT__ib_c;
        QData/*33:0*/ fftmain__DOT__stage_512__DOT__pre_ovalue;
        QData/*39:0*/ fftmain__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*34:0*/ fftmain__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*34:0*/ fftmain__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*38:0*/ fftmain__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*38:0*/ fftmain__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*34:0*/ fftmain__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*38:0*/ fftmain__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*38:0*/ fftmain__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*36:0*/ fftmain__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*36:0*/ fftmain__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*38:0*/ fftmain__DOT__stage_512__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*33:0*/ fftmain__DOT__stage_256__DOT__ib_a;
        QData/*33:0*/ fftmain__DOT__stage_256__DOT__ib_b;
        QData/*41:0*/ fftmain__DOT__stage_256__DOT__ib_c;
        QData/*35:0*/ fftmain__DOT__stage_256__DOT__pre_ovalue;
        QData/*33:0*/ fftmain__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*33:0*/ fftmain__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_right;
    };
    struct {
        QData/*41:0*/ fftmain__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*36:0*/ fftmain__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*36:0*/ fftmain__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*40:0*/ fftmain__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*40:0*/ fftmain__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*36:0*/ fftmain__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*40:0*/ fftmain__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*40:0*/ fftmain__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*38:0*/ fftmain__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*38:0*/ fftmain__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*40:0*/ fftmain__DOT__stage_256__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*35:0*/ fftmain__DOT__stage_128__DOT__ib_a;
        QData/*35:0*/ fftmain__DOT__stage_128__DOT__ib_b;
        QData/*43:0*/ fftmain__DOT__stage_128__DOT__ib_c;
        QData/*35:0*/ fftmain__DOT__stage_128__DOT__pre_ovalue;
        QData/*35:0*/ fftmain__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*35:0*/ fftmain__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        QData/*43:0*/ fftmain__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*38:0*/ fftmain__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*38:0*/ fftmain__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*42:0*/ fftmain__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*42:0*/ fftmain__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*38:0*/ fftmain__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*42:0*/ fftmain__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*42:0*/ fftmain__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*40:0*/ fftmain__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*40:0*/ fftmain__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*42:0*/ fftmain__DOT__stage_128__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*35:0*/ fftmain__DOT__stage_64__DOT__ib_a;
        QData/*35:0*/ fftmain__DOT__stage_64__DOT__ib_b;
        QData/*43:0*/ fftmain__DOT__stage_64__DOT__ib_c;
        QData/*37:0*/ fftmain__DOT__stage_64__DOT__pre_ovalue;
        QData/*35:0*/ fftmain__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*35:0*/ fftmain__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        QData/*43:0*/ fftmain__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*38:0*/ fftmain__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*38:0*/ fftmain__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*42:0*/ fftmain__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*42:0*/ fftmain__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*38:0*/ fftmain__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*42:0*/ fftmain__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*42:0*/ fftmain__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*40:0*/ fftmain__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*40:0*/ fftmain__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*42:0*/ fftmain__DOT__stage_64__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*37:0*/ fftmain__DOT__stage_32__DOT__ib_a;
        QData/*37:0*/ fftmain__DOT__stage_32__DOT__ib_b;
        QData/*45:0*/ fftmain__DOT__stage_32__DOT__ib_c;
        QData/*37:0*/ fftmain__DOT__stage_32__DOT__pre_ovalue;
        QData/*37:0*/ fftmain__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*37:0*/ fftmain__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        QData/*45:0*/ fftmain__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*40:0*/ fftmain__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*40:0*/ fftmain__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*44:0*/ fftmain__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*44:0*/ fftmain__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*40:0*/ fftmain__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*44:0*/ fftmain__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*44:0*/ fftmain__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*42:0*/ fftmain__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*42:0*/ fftmain__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*44:0*/ fftmain__DOT__stage_32__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*37:0*/ fftmain__DOT__stage_16__DOT__ib_a;
        QData/*37:0*/ fftmain__DOT__stage_16__DOT__ib_b;
    };
    struct {
        QData/*45:0*/ fftmain__DOT__stage_16__DOT__ib_c;
        QData/*39:0*/ fftmain__DOT__stage_16__DOT__pre_ovalue;
        QData/*37:0*/ fftmain__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*37:0*/ fftmain__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        QData/*45:0*/ fftmain__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*40:0*/ fftmain__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*40:0*/ fftmain__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*44:0*/ fftmain__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*44:0*/ fftmain__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*40:0*/ fftmain__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*44:0*/ fftmain__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*44:0*/ fftmain__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*42:0*/ fftmain__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*42:0*/ fftmain__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*44:0*/ fftmain__DOT__stage_16__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*39:0*/ fftmain__DOT__stage_8__DOT__ib_a;
        QData/*39:0*/ fftmain__DOT__stage_8__DOT__ib_b;
        QData/*47:0*/ fftmain__DOT__stage_8__DOT__ib_c;
        QData/*39:0*/ fftmain__DOT__stage_8__DOT__pre_ovalue;
        QData/*39:0*/ fftmain__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_left;
        QData/*39:0*/ fftmain__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_right;
        QData/*47:0*/ fftmain__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__r_coef;
        QData/*42:0*/ fftmain__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__leftv;
        QData/*42:0*/ fftmain__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__leftvv;
        QData/*46:0*/ fftmain__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__w_one;
        QData/*46:0*/ fftmain__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__w_two;
        QData/*42:0*/ fftmain__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__left_saved;
        QData/*46:0*/ fftmain__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__mpy_r;
        QData/*46:0*/ fftmain__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__mpy_i;
        QData/*44:0*/ fftmain__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_one;
        QData/*44:0*/ fftmain__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_two;
        QData/*46:0*/ fftmain__DOT__stage_8__DOT__HWBFLY__DOT__bfly__DOT__CKPCE_ONE__DOT__rp_three;
        QData/*41:0*/ fftmain__DOT__stage_4__DOT__ob_a;
        VlUnpacked<QData/*39:0*/, 256> fftmain__DOT__stage_512__DOT__cmem;
        VlUnpacked<IData/*31:0*/, 256> fftmain__DOT__stage_512__DOT__imem;
        VlUnpacked<QData/*33:0*/, 256> fftmain__DOT__stage_512__DOT__omem;
        VlUnpacked<QData/*41:0*/, 128> fftmain__DOT__stage_256__DOT__cmem;
        VlUnpacked<QData/*33:0*/, 128> fftmain__DOT__stage_256__DOT__imem;
        VlUnpacked<QData/*35:0*/, 128> fftmain__DOT__stage_256__DOT__omem;
        VlUnpacked<QData/*43:0*/, 64> fftmain__DOT__stage_128__DOT__cmem;
        VlUnpacked<QData/*35:0*/, 64> fftmain__DOT__stage_128__DOT__imem;
        VlUnpacked<QData/*35:0*/, 64> fftmain__DOT__stage_128__DOT__omem;
        VlUnpacked<QData/*43:0*/, 32> fftmain__DOT__stage_64__DOT__cmem;
        VlUnpacked<QData/*35:0*/, 32> fftmain__DOT__stage_64__DOT__imem;
        VlUnpacked<QData/*37:0*/, 32> fftmain__DOT__stage_64__DOT__omem;
        VlUnpacked<QData/*45:0*/, 16> fftmain__DOT__stage_32__DOT__cmem;
        VlUnpacked<QData/*37:0*/, 16> fftmain__DOT__stage_32__DOT__imem;
        VlUnpacked<QData/*37:0*/, 16> fftmain__DOT__stage_32__DOT__omem;
        VlUnpacked<QData/*45:0*/, 8> fftmain__DOT__stage_16__DOT__cmem;
        VlUnpacked<QData/*37:0*/, 8> fftmain__DOT__stage_16__DOT__imem;
        VlUnpacked<QData/*39:0*/, 8> fftmain__DOT__stage_16__DOT__omem;
        VlUnpacked<QData/*47:0*/, 4> fftmain__DOT__stage_8__DOT__cmem;
        VlUnpacked<QData/*39:0*/, 4> fftmain__DOT__stage_8__DOT__imem;
        VlUnpacked<QData/*39:0*/, 4> fftmain__DOT__stage_8__DOT__omem;
        VlUnpacked<QData/*39:0*/, 2> fftmain__DOT__stage_4__DOT__imem;
        VlUnpacked<QData/*41:0*/, 2> fftmain__DOT__stage_4__DOT__omem;
        VlUnpacked<QData/*41:0*/, 1024> fftmain__DOT__revstage__DOT__brmem;
        VlUnpacked<CData/*0:0*/, 2> __Vm_traceActivity;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<1> __VactTriggered;
    VlTriggerVec<1> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vfftmain__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vfftmain___024root(Vfftmain__Syms* symsp, const char* v__name);
    ~Vfftmain___024root();
    VL_UNCOPYABLE(Vfftmain___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
